os:
  - windows
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
install:
  - pip install git+https://github.com/naftulikay/travis-pls
  - travis-pls python tools/build.py build
  - cargo build -vv
script:
  - cargo run