os:
  - windows
  - linux
  - osx
language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then wget --quiet https://curl.haxx.se/ca/cacert.pem; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export SSL_CERT_FILE=$HOME/cacert.pem; fi
  - python tools/build.py build
  - cargo build -vv
script:
  - cargo run