image: macOS

environment:
  RUSTUP_HOME: /usr/local/rustup
  CARGO_HOME: /usr/local/cargo
  RUST_VERSION: '1.43.0'

build_script:
  - export PATH="/usr/local/cargo/bin:$PATH"
  - wget https://static.rust-lang.org/rustup/archive/1.21.1/x86_64-apple-darwin/rustup-init
  - chmod +x rustup-init
  - ./rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION
  - rm rustup-init
  - chmod -R a+w $RUSTUP_HOME $CARGO_HOME
  - rustup --version
  - cargo --version
  - rustc --version
  - python ./tools/build.py build --debug
  - python ./tools/build.py build

artifacts:
  - path: out/x86_64-apple-darwin
    type: zip
