version: 2.1
jobs:
  build:
    docker:
      - image: hackzzila/webrtc-env:latest
        environment:
          TAR_OPTIONS: --no-same-owner
    steps:
      - checkout
      - restore_cache:
          key: webrtc
      - run:
          name: "C++ Debug Build"
          command: python ./tools/build.py build --debug
      - save_cache:
          key: webrtc
          paths:
            - ~/project/deps
