name: build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [Windows, Linux]
    steps:
    - uses: actions/checkout@v2

    - name: Setup Build Cache on Linux
      if: matrix.os == 'Linux'
      run: mkdir -p ~/actions-cache && ln -s ~/actions-cache ./deps

    - name: Setup Build Cache on Windows
      if: matrix.os == 'Windows'
      run: mklink /D .\deps C:\actions-cache
      shell: cmd

    - name: Build C++ Debug
      run: python ./tools/build.py build --debug

    - name: Build C++ Release
      run: python ./tools/build.py build --debug

    - name: Build Rust Debug
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Build Rust Release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    # - name: Test
    #   uses: actions-rs/cargo@v1
    #   with:
    #     command: test
    #     args: --release --workspace
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}
        path: build
